export type SET_GAME_STATE = 'CONFIG_SET_GAME_STATE';
export const SET_GAME_STATE: SET_GAME_STATE = 'CONFIG_SET_GAME_STATE';

export type SET_NICKNAME = 'CONFIG_SET_NICKNAME';
export const SET_NICKNAME: SET_NICKNAME = 'CONFIG_SET_NICKNAME';

export type SUBMIT_NICKNAME = 'CONFIG_SUBMIT_NICKNAME';
export const SUBMIT_NICKNAME: SUBMIT_NICKNAME = 'CONFIG_SUBMIT_NICKNAME';