name: CI
on: [push]
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install
        run: yarn install
      - name: Deploy
        run: yarn deploy:ci
        env:
          FIREBASE_DEPLOY_TOKEN: ${{secrets.FIREBASE_DEPLOY_TOKEN}}
